name = "coupleconnect"
compatibility_date = "2024-09-01"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "coupleconnect-db"
database_id = "713d60fd-b501-4e27-9820-d7a967fb11e7"
